"""
Client installer endpoint - serves one-liner installation script
"""
from fastapi import APIRouter, Response, Request
from fastapi.responses import PlainTextResponse
from logs.logger import system_logger
from settings import settings

router = APIRouter(tags=["Client Installer"])


@router.get("/client.sh")
async def get_client_installer_bash(request: Request):
    """
    Serves a bash one-liner that downloads and runs the Python client

    Usage:
        curl https://ngrok.424th.com/client.sh | bash -s -- --port 3000 --api-key YOUR_KEY

    Or with custom options:
        curl https://ngrok.424th.com/client.sh | bash -s -- \\
            --port 8080 \\
            --api-key YOUR_API_KEY \\
            --name "my-app" \\
            --https
    """
    # Get the server host from request
    server_host = request.headers.get("host", "localhost:8989")
    protocol = "https" if settings.ENVIRONMENT == "PROD" else "http"

    script = f'''#!/bin/bash
# Tunnel Client Installer
# Auto-generated by {settings.APP_NAME}

set -e

echo "=========================================="
echo "  Tunnel Client Installer"
echo "=========================================="
echo ""

# Check for Python
if ! command -v python3 &> /dev/null; then
    echo "Error: python3 is required but not installed"
    exit 1
fi

# Check for required Python packages
echo "Checking dependencies..."
if ! python3 -c "import httpx" 2>/dev/null; then
    echo "Installing httpx..."
    pip3 install httpx --quiet
fi

if ! python3 -c "import websockets" 2>/dev/null; then
    echo "Installing websockets..."
    pip3 install websockets --quiet
fi

echo "Dependencies OK"
echo ""

# Download client script
echo "Downloading tunnel client..."
TEMP_CLIENT="/tmp/tunnel_client_$$.py"
cat > "$TEMP_CLIENT" << 'EOFCLIENT'
'''

    # Read the actual client code
    try:
        with open('/root/NGROK_TUNNEL/client/tunnel_client.py', 'r') as f:
            client_code = f.read()
    except Exception as e:
        system_logger.error(f"Failed to read client code: {e}")
        client_code = "# Error: Could not load client code"

    script += client_code

    script += f'''
EOFCLIENT

echo "Client downloaded"
echo ""

# Determine protocol based on environment
{"USE_HTTPS=true" if settings.ENVIRONMENT == "PROD" else "USE_HTTPS=false"}

# Parse arguments and run
echo "Starting tunnel client..."
echo "Server: {server_host}"
echo ""

if [ "$USE_HTTPS" = true ]; then
    python3 "$TEMP_CLIENT" --server {server_host} --https "$@"
else
    python3 "$TEMP_CLIENT" --server {server_host} "$@"
fi

# Cleanup
rm -f "$TEMP_CLIENT"
'''

    return PlainTextResponse(content=script, media_type="text/x-shellscript")


@router.get("/client.py")
async def get_client_python(request: Request):
    """
    Serves the raw Python client for direct download

    Usage:
        curl https://ngrok.424th.com/client.py -o tunnel_client.py
        python3 tunnel_client.py --server ngrok.424th.com --api-key KEY --port 3000 --https

    Or one-liner:
        python3 <(curl -s https://ngrok.424th.com/client.py) \\
            --server ngrok.424th.com --api-key KEY --port 3000 --https
    """
    try:
        with open('/root/NGROK_TUNNEL/client/tunnel_client.py', 'r') as f:
            client_code = f.read()

        return PlainTextResponse(content=client_code, media_type="text/x-python")
    except Exception as e:
        system_logger.error(f"Failed to read client code: {e}")
        return PlainTextResponse(
            content=f"# Error loading client: {{e}}",
            status_code=500
        )


@router.get("/install")
async def get_install_instructions(request: Request):
    """
    Shows installation instructions
    """
    server_host = request.headers.get("host", "localhost:8989")
    protocol = "https" if settings.ENVIRONMENT == "PROD" else "http"

    instructions = f'''Tunnel Client - Installation Instructions
{'='*50}

Quick Start (One-liner):
{'='*50}

Bash one-liner (recommended):
  curl {protocol}://{server_host}/client.sh | bash -s -- \\
    --api-key YOUR_API_KEY \\
    --port 3000

With custom name:
  curl {protocol}://{server_host}/client.sh | bash -s -- \\
    --api-key YOUR_API_KEY \\
    --port 8080 \\
    --name "my-app"

{'='*50}
Alternative: Download and run manually
{'='*50}

1. Download client:
   curl {protocol}://{server_host}/client.py -o tunnel_client.py

2. Run client:
   python3 tunnel_client.py \\
     --server {server_host} \\
     --api-key YOUR_API_KEY \\
     --port 3000{'\\' if settings.ENVIRONMENT == "PROD" else ''}
     {'--https' if settings.ENVIRONMENT == "PROD" else ''}

{'='*50}
Python one-liner:
{'='*50}

  python3 <(curl -s {protocol}://{server_host}/client.py) \\
    --server {server_host} \\
    --api-key YOUR_API_KEY \\
    --port 3000{'\\' if settings.ENVIRONMENT == "PROD" else ''}
    {'--https' if settings.ENVIRONMENT == "PROD" else ''}

{'='*50}
Required Arguments:
{'='*50}

  --server {server_host}   Server address
  --api-key YOUR_KEY          API key for authentication
  --port PORT                 Local port to tunnel

Optional Arguments:
{'='*50}

  --name NAME                 Friendly name for tunnel
  --host HOST                 Local host (default: localhost)
  --https                     Use HTTPS/WSS (for production)

{'='*50}
API Endpoint:
{'='*50}

  Base URL: {protocol}://{server_host}
  Health: {protocol}://{server_host}/health
  Docs: {protocol}://{server_host}/docs

{'='*50}
'''

    return PlainTextResponse(content=instructions)
